version: '2'
services:
  proxy:
    image: traefik
    command: --api --docker --docker.watch=true --docker.exposedbydefault=false --docker.domain=localhost --logLevel=WARN
    # labels:
    #  - "traefik.enable=true"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /dev/null:/traefik.toml
  cache:
    restart: always
    image: redis:3-alpine
    volumes:
     - cache_data:/data
    expose:
     - 6379
    ports:
     - 6379
  nosql:
    restart: always
    image: moalmeida/docker-mongo:0.0.0
    volumes:
     - nosql_data:/data/db
    command: mongod --smallfiles
    expose:
     - 27017
    ports:
     - 27017
  api:
    restart: always
    build: .
    labels:
     - "traefik.enable=true"
     - "traefik.backend=api.example"
     - "traefik.frontend.rule=Host:api.example"
    environment:
     - PORT=8888
     - NODE_ENV=development
     - CACHE_HOST=cache
     - CACHE_PORT=6379
     - NOSQL_HOST=nosql
     - NOSQL_PORT=27017
     - NOSQL_DB=example
    expose:
     - 8888
    ports:
     - 8888:8888
    depends_on:
     - cache
     - nosql
    links:
     - cache
     - nosql
    privileged: true
volumes:
  nosql_data: {}
  cache_data: {}
